/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fxqcqutmyjkobnzptlxt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4cWNxdXRteWprb2JuenB0bHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDE1MjcsImV4cCI6MjA3MjcxNzUyN30.GynU71-y-jS0Fx6AGXVq-QhLt_yAoTGhSw-iXZuj4eg"